# NumPy Exercise 

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [7]:
arr=np.zeros(10)

#### Create an array of 10 ones

In [8]:
arr=np.ones(19)

#### Create an array of 10 fives

In [9]:
arr=np.ones(10)*5

#### Create an array of the integers from 10 to 50

In [12]:
arr=np.arange(10,50)

#### Create an array of all the even integers from 10 to 50

In [17]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
arr=np.arange(9)
arr=arr.reshape(3,3)

#### Create a 3x3 identity matrix

In [21]:
arr=np.eye(3)

#### Use NumPy to generate a random number between 0 and 1

In [47]:
arr=np.random.random()

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [50]:
np.random.randn(25)

array([-0.63543585, -0.50432982, -0.72047959, -0.9791328 , -1.40088853,
        0.63116661, -0.15248984, -1.08965643,  2.12950948,  0.84035488,
       -0.60799119, -1.23688004, -0.05966897, -0.66299231, -0.65609888,
       -0.53289491,  1.43722232, -0.20547634,  0.06949599, -0.50247685,
       -0.57656465,  0.9506341 ,  0.86076385, -0.64452891, -0.54757137])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [53]:
np.linspace(0,1,20,endpoint=True)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

In [89]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [87]:
np.array([[12,13,14,15],[17,18,19,20],[22,23,24,25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [70]:
arr[1,3]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [72]:
np.array([[2],[7],[12]])

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [73]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [83]:
a=np.arange(16, 26)
a.reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [90]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [92]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [96]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])